name: Cleanup PR Preview

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  #v6.0.2
        with:
          ref: gh-pages

      - name: Remove preview folder
        run: |
          PR=${{ github.event.pull_request.number }}
          TARGET="_preview/$PR"

          if [ -d "$TARGET" ]; then
            rm -rf "$TARGET"
          else
            echo "No preview found"
          fi

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9  #v7.1.0
        with:
          branch: gh-pages
          commit_message: Delete preview for pull request \#${{ github.event.pull_request.number }}